
os: osx
osx_image: xcode7.3

env:
  R_VERSION: 3.6.1
  FC: /usr/local/gfortran/bin/gfortran
  CRAN_MIRROR: https://cran.microsoft.com/snapshot/2020-01-01

install:
#  - curl -o clang.pkg https://cloud.r-project.org/bin/macosx/tools/clang-7.0.0.pkg
#  - sudo installer -pkg clang.pkg -target /
  - curl -o gfortran.pkg https://cloud.r-project.org/bin/macosx/tools/gfortran-6.1.pkg
  - sudo installer -pkg gfortran.pkg -target /
  - curl -o XQuartz.pkg https://www.jamovi.org/misc/XQuartz.pkg
  - sudo installer -package XQuartz.pkg -target /
  - curl https://cloud.r-project.org/src/base/R-3/R-$R_VERSION.tar.gz | tar xz
  - curl -o xz.tar.gz https://mac.r-project.org/libs/xz-5.2.3-darwin.15-x86_64.tar.gz
  - sudo tar fxzk xz.tar.gz -C / || true
#   - curl https://mac.r-project.org/libs/pcre-8.40-darwin.15-x86_64.tar.gz | sudo tar xzk -C / || true
  - curl https://mac.r-project.org/libs/pixman-0.32.6-darwin.13-x86_64.tar.gz | sudo tar xzk -C / || true
  - curl https://mac.r-project.org/libs/fontconfig-2.11.1-darwin.13-x86_64.tar.gz | sudo tar xzk -C / || true
  - curl https://mac.r-project.org/libs/freetype-2.5.5-darwin.13-x86_64.tar.gz | sudo tar xzk -C / || true
  - curl https://mac.r-project.org/libs/cairo-1.14.2-darwin.13-x86_64.tar.gz | sudo tar xzk -C / || true
#  - brew install libxml2
#  - sudo /usr/libexec/locate.updatedb
#  - locate libxml-2.0.pc
#  - export PKG_CONFIG_PATH=/usr/lib/pkgconfig:/usr/local/lib/pkgconfig:/usr/local/Cellar/libxml2/2.9.4/lib/pkgconfig
#  - pkg-config --exists cairo --print-errors
#   - curl https://mac.r-project.org/libs/libpng-1.6.28-darwin.15-x86_64.tar.gz | sudo tar xzk -C /
#   - curl https://mac.r-project.org/libs/jpeg-9-darwin.15-x86_64.tar.gz | sudo tar xzk -C /
#   - curl https://mac.r-project.org/libs/tiff-4.0.7-darwin.15-x86_64.tar.gz | sudo tar xzk -C /
#   - curl https://mac.r-project.org/libs/readline-5.2-12-darwin8-bin4.tar.gz | sudo tar xzk -C /
#   - curl https://mac.r-project.org/libs/libiomp-20131213-darwin10.tar.gz | sudo tar xzk -C /
#   - sudo ditto usr/local /usr/local
#   - sudo rm -rf /Library/Frameworks/R.framework
  - curl -o R.pkg https://cloud.r-project.org/bin/macosx/R-$R_VERSION.pkg
  - sudo installer -pkg R.pkg -target /
  - cp /Library/Frameworks/R.framework/Versions/3.6/Resources/lib/libc++.1.dylib .
  - cp /Library/Frameworks/R.framework/Versions/3.6/Resources/lib/libc++abi.1.dylib .
  - cp /Library/Frameworks/R.framework/Versions/3.6/Resources/lib/libomp.dylib .
  - sudo rm -rf /Library/Frameworks/R.framework

script:

  - cd R-$R_VERSION
  
  - cat configure | grep -v "#include <cairo-xlib.h>" >tmp
  - cat tmp >configure
  - rm tmp
  
  - export PKG_CONFIG_PATH=/usr/lib/pkgconfig:/usr/local/lib/pkgconfig:/usr/local/Cellar/libxml2/2.9.4/lib/pkgconfig

  - ./configure 'CC=clang' 'CXX=clang++' 'OBJC=clang' 'CFLAGS=-Wall -g -O2' 'CPPFLAGS=-isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk -I/usr/local/include' 'CXXFLAGS=-Wall -g -O2' 'OBJCFLAGS=-Wall -g -O2' 'FCFLAGS=-Wall -g -O2' 'F77FLAGS=-Wall -g -O2' --enable-R-framework --enable-R-shlib --with-aqua=no --with-tcltk=no --with-x=no --with-cairo=yes --with-libpng=yes --with-jpeglib=yes --with-libtiff=yes
  - make
  - sudo make install
  - cd ..
  
  - ditto /Library/Frameworks/R.framework R.framework
  - cp libc++.1.dylib    R.framework/Versions/3.6/Resources/lib
  - cp libc++abi.1.dylib R.framework/Versions/3.6/Resources/lib
  - cp libomp.dylib      R.framework/Versions/3.6/Resources/lib
  
  - mkdir -p R.framework/Resources/base
  - mkdir -p R.framework/Resources/base/R
  - /Library/Frameworks/R.framework/Resources/bin/R -e "install.packages(c('Rcpp', 'RInside'), repos='$CRAN_MIRROR', lib='R.framework/Resources/library', type='mac.binary.el-capitan')"
  - /Library/Frameworks/R.framework/Resources/bin/R -e "install.packages(c('rjson', 'base64enc', 'RProtoBuf', 'knitr', 'testthat', 'rlang', 'ggplot2', 'remotes'), repos='$CRAN_MIRROR', lib='R.framework/Resources/base/R', type='mac.binary.el-capitan')"
  
  - python patch-framework.py
  - install_name_tool -change /Library/Frameworks/R.framework/Versions/3.6/Resources/lib/libc++abi.1.dylib @executable_path/../Frameworks/R.framework/Versions/3.6/Resources/lib/libc++abi.1.dylib R.framework/Versions/3.6/Resources/lib/libc++.1.dylib
  - mv R.framework/Resources/base .
  
  - echo "#!/bin/sh"                              >tmp
  - echo "# Shell wrapper for R executable."      >>tmp
  - echo HERE=\$\(cd \"\$\(dirname \"\$0\"\)\"\; pwd\) >>tmp
  - echo export R_HOME=\$HERE/..                  >>tmp
  - echo export R_SHARE_DIR=\$R_HOME/share        >>tmp
  - echo export R_INCLUDE_DIR=\$R_HOME/include    >>tmp
  - echo export R_DOC_DIR=\$R_HOME/doc            >>tmp
  - tail -n +41 R.framework/Versions/Current/Resources/bin/R >>tmp
  - cat tmp >R.framework/Versions/Current/Resources/bin/R
  - rm tmp
  
  - mkdir -p artifacts
  - tar -cjf artifacts/R.framework.tar.bz2  R.framework
  - tar -cjf artifacts/base.tar.bz2         base
  
deploy:
  - provider: s3
    bucket: jamovi-library
    region: us-east-1
    access_key_id:
      secure: "IaAionaTUStZ9cH5eGUBGr6VE8U1TDzkD8/BP1Vh+B4gOhXmKHkm1L5EDO/icQEsLsX+oZXokMA7eSoP5VocQzO41jIRmMHPu6Mmj38DO9UTGY5LyN2arSLjjk1aOH48vvEZQ51IeaOwqARJmpGSjFCQsgCjW5Ae8imZUaPqtmO60i84iDl/aRdlaDnUkDcpn+YqZKjbzz8Dn+4JfUOkBwfINKgJO5q6jkEZeXkRz+jISVvYxME7G3pFtkjaLhb0TtFkU9D+eCZhDu0vq/+yIfnDI84kpUIZVfDutKlsORVjeHY+TSpvsYWOXqNbrSYy9qMrB0LSXpYjFHN9d3r2jKExMhG22YbtM50r1ZewYTZ0s2bkJZVNLw7TRks39/LSQeVTKXgEgIPsz7OWBbK3PRewF8BWu+la3JZsDOIDyjDACbru4aiIlmpjIfaurscTKaj5E87s8zBJFGGRpVBjxzqoI0xng207KCZ8PbCeBGQsHmZS+KG9C1VIplTevs4iVOcqgthe8P4+jwNj18DDQ+DUfN8ZvTMBF+2/txbDrL1lgnM87A5IRSk1NwxnwH+VbGztU/tnGYWivvf6vI47mQS+JN3zdXvfSPWAoSn5bXJ9kiNdK7F3hVKmHxnwQH08KECwm/NlAhTu3/Py+I+QpK5znJkKppj8V/EqioKhC+c="
    secret_access_key:
      secure: "mGQp8vP7cVDXMt7f5tuYl/FB3FCFGZav1CWI8XkG7fYic0SJWZyFdnXNyWvvFOrr/haTn5XtSM454TAvmTQehL5aXV/bKc36j1ZK5xG3xPVOTxwsVssLQ07BXCZYdAIrQ4/l7S1fWW/bdODhq7IYVa1Dew9bHatijUpDuNHe8BgWExNJ0NhKOIVBIXJPRbxv8WpPWUb0oq3ZXjmUUxjx2Ohi6GwFktuqtLx75Cevkh+pUQoHJ9kMPWHdieJOkWJdmPVemzi9j49jwccrFEKAnBkrujdRuAVvpodwQth8wt/GbUVuTwbUQt1+A7VeN8Fvn/246nWNoHfnZLQkO91djAwuTjW2sludbBZfRG+CI2SV9a5NzCzLQtKA7RzjkZDQiw8JrBcokRmL6BPjUxC6YPmKuPxBnhJyENUPRcUGjMRIADSO7jEQ5vqO0gcKSXtvu0yv/I7zMao9wq23hIuR+sBytg7hpsSl2EFkqP7sZkK9G/znfci5Ow0aID9+xZQgxqPPBEA0gHnpDDveh/XwKnnGTZRINKbZPFWJoY8TRKlDDOkFlVoncX03ONMLDEGA8KOfT7Dmgl8HGmujF58qQMUUxBvxSIBMg7LDIAEa2mQUWXE8sFoHwvgqrooBWI4WVtwonzZJSi/xSjFiD+K24lYkKqgCTfOmJlx2bqz60CM=" 
    skip_cleanup: true
    upload-dir: travis-builds
    local_dir: artifacts
  
  
