
os: osx
osx_image: xcode8

env:
  R_VERSION: 3.6.1

before_install:
  - curl -o clang.pkg https://cloud.r-project.org/bin/macosx/tools/clang-7.0.0.pkg
  - sudo installer -pkg clang.pkg -target /
  - curl -o gfortran.pkg https://cloud.r-project.org/bin/macosx/tools/gfortran-6.1.pkg
  - sudo installer -pkg gfortran.pkg -target /
  - curl -o XQuartz.pkg https://www.jamovi.org/misc/XQuartz.pkg
  - sudo installer -package XQuartz.pkg -target /
  - curl https://cloud.r-project.org/src/base/R-3/R-$R_VERSION.tar.gz | tar xz
  - curl https://mac.r-project.org/libs/pcre-8.40-darwin.15-x86_64.tar.gz | tar xz
  - curl https://mac.r-project.org/libs/pixman-0.32.6-darwin.13-x86_64.tar.gz | tar xz
  - curl https://mac.r-project.org/libs/fontconfig-2.11.1-darwin.13-x86_64.tar.gz | tar xz
  - curl https://mac.r-project.org/libs/freetype-2.5.5-darwin.13-x86_64.tar.gz | tar xz
  - curl https://mac.r-project.org/libs/cairo-1.14.2-darwin.13-x86_64.tar.gz | tar xz
  - curl https://mac.r-project.org/libs/libpng-1.6.28-darwin.15-x86_64.tar.gz | tar xz
  - curl https://mac.r-project.org/libs/jpeg-9-darwin.15-x86_64.tar.gz | tar xz
  - curl https://mac.r-project.org/libs/tiff-4.0.7-darwin.15-x86_64.tar.gz | tar xz
  - curl https://mac.r-project.org/libs/readline-5.2-12-darwin8-bin4.tar.gz | tar xz
  - curl https://mac.r-project.org/libs/libiomp-20131213-darwin10.tar.gz | tar xz
  - sudo chown -R $(whoami) /usr/local
  - sudo ditto usr/local /usr/local
#   - sudo rm -rf /Library/Frameworks/R.framework
  - curl -o R.pkg https://cloud.r-project.org/bin/macosx/R-$R_VERSION.pkg
  - sudo installer -pkg R.pkg -target /
  - cp /Library/Frameworks/R.framework/Versions/3.6/Resources/lib/libc++.1.dylib .
  - cp /Library/Frameworks/R.framework/Versions/3.6/Resources/lib/libc++abi.1.dylib .
  - cp /Library/Frameworks/R.framework/Versions/3.6/Resources/lib/libomp.dylib .
  - sudo rm -rf /Library/Frameworks/R.framework
