
os: osx
osx_image: xcode11.3

env:
  R_VERSION: 4.0.2
  CRAN_MIRROR: https://cran.microsoft.com/snapshot/2020-08-24

install:

  - brew install marcelomazza/homebrew-curl-libssh2/curl

  - curl -o R.pkg https://cloud.r-project.org/bin/macosx/R-$R_VERSION.pkg
  - sudo installer -pkg R.pkg -target /

script:

  - ditto /Library/Frameworks/R.framework R.framework
  - rm -f R.framework/Versions/4.0/Resources/fontconfig/fonts/conf.d/*
  - cp /Library/Frameworks/R.framework/Versions/4.0/Resources/fontconfig/fonts/conf.d/* R.framework/Versions/4.0/Resources/fontconfig/fonts/conf.d/
  - mkdir -p R.framework/Resources/base
  - mkdir -p R.framework/Resources/base/R

  - /Library/Frameworks/R.framework/Resources/bin/R -e "install.packages(c('R6', 'RColorBrewer', 'base64enc', 'bitops', 'curl', 'fansi', 'farver', 'highr', 'labeling', 'magrittr', 'praise', 'prettyunits', 'rlang', 'rstudioapi', 'systemfonts', 'utf8', 'viridisLite', 'yaml', 'RCurl', 'Rcpp', 'assertthat', 'backports', 'colorspace', 'crayon', 'digest', 'ellipsis', 'evaluate', 'glue', 'gtable', 'jsonlite', 'mime', 'pkgconfig', 'ps', 'ragg', 'remotes', 'stringi', 'withr', 'xfun', 'RInside', 'RProtoBuf', 'cli', 'htmltools', 'lifecycle', 'markdown', 'munsell', 'processx', 'rprojroot', 'stringr', 'tinytex', 'vctrs', 'callr', 'desc', 'knitr', 'pillar', 'scales', 'pkgbuild', 'rmarkdown', 'tibble', 'pkgload', 'testthat', 'isoband', 'ggplot2'), repos='$CRAN_MIRROR', lib='R.framework/Resources/base/R', type='mac.binary')"

  - python patch-framework.py
  - install_name_tool -change @executable_path/../Frameworks/R.framework/Versions/4.0/Resources/lib/libR.dylib      @executable_path/../../lib/libR.dylib      R.framework/Versions/4.0/Resources/bin/exec/R
  - install_name_tool -change @executable_path/../Frameworks/R.framework/Versions/4.0/Resources/lib/libRblas.dylib  @executable_path/../../lib/libRblas.dylib  R.framework/Versions/4.0/Resources/bin/exec/R
  - install_name_tool -id @executable_path/../Resources/modules/base/R/RInside/lib/libRInside.dylib   R.framework/Resources/base/R/RInside/lib/libRInside.dylib
  - install_name_tool -id @executable_path/../Resources/modules/base/R/RInside/libs/RInside.so        R.framework/Resources/base/R/RInside/libs/RInside.so
  - install_name_tool -id @executable_path/../Resources/modules/base/R/Rcpp/libs/Rcpp.so              R.framework/Resources/base/R/Rcpp/libs/Rcpp.so
  - codesign --remove-signature R.framework/Versions/4.0/Resources/bin/exec/R
  - mv R.framework/Resources/base .
  
  - echo "#!/bin/sh"                              >tmp
  - echo "# Shell wrapper for R executable."      >>tmp
  - echo HERE=\$\(cd \"\$\(dirname \"\$0\"\)\"\; pwd\) >>tmp
  - echo export R_HOME=\$HERE/..                  >>tmp
  - echo export R_SHARE_DIR=\$R_HOME/share        >>tmp
  - echo export R_INCLUDE_DIR=\$R_HOME/include    >>tmp
  - echo export R_DOC_DIR=\$R_HOME/doc            >>tmp
  - tail -n +41 R.framework/Versions/Current/Resources/bin/R >>tmp
  - cat tmp >R.framework/Versions/Current/Resources/bin/R
  - rm tmp
  
  - mkdir -p artifacts
  - tar -cjf artifacts/R.framework.tar.bz2  R.framework
  - tar -cjf artifacts/base.tar.bz2         base

after_success:
  - echo "${SFTP_KEY}" | base64 --decode >/tmp/sftp_rsa
  - /usr/local/opt/curl/bin/curl
         --ftp-create-dirs
         --insecure
         --key /tmp/sftp_rsa
         -T "artifacts/{R.framework,base}.tar.bz2"
         sftp://${SFTP_USER}@jamovi.org/home/${SFTP_USER}/jamovi.org/downloads/

# deploy:
#   - provider: s3
#     bucket: jamovi-library
#     region: us-east-1
#     access_key_id:
#       secure: "IaAionaTUStZ9cH5eGUBGr6VE8U1TDzkD8/BP1Vh+B4gOhXmKHkm1L5EDO/icQEsLsX+oZXokMA7eSoP5VocQzO41jIRmMHPu6Mmj38DO9UTGY5LyN2arSLjjk1aOH48vvEZQ51IeaOwqARJmpGSjFCQsgCjW5Ae8imZUaPqtmO60i84iDl/aRdlaDnUkDcpn+YqZKjbzz8Dn+4JfUOkBwfINKgJO5q6jkEZeXkRz+jISVvYxME7G3pFtkjaLhb0TtFkU9D+eCZhDu0vq/+yIfnDI84kpUIZVfDutKlsORVjeHY+TSpvsYWOXqNbrSYy9qMrB0LSXpYjFHN9d3r2jKExMhG22YbtM50r1ZewYTZ0s2bkJZVNLw7TRks39/LSQeVTKXgEgIPsz7OWBbK3PRewF8BWu+la3JZsDOIDyjDACbru4aiIlmpjIfaurscTKaj5E87s8zBJFGGRpVBjxzqoI0xng207KCZ8PbCeBGQsHmZS+KG9C1VIplTevs4iVOcqgthe8P4+jwNj18DDQ+DUfN8ZvTMBF+2/txbDrL1lgnM87A5IRSk1NwxnwH+VbGztU/tnGYWivvf6vI47mQS+JN3zdXvfSPWAoSn5bXJ9kiNdK7F3hVKmHxnwQH08KECwm/NlAhTu3/Py+I+QpK5znJkKppj8V/EqioKhC+c="
#     secret_access_key:
#       secure: "mGQp8vP7cVDXMt7f5tuYl/FB3FCFGZav1CWI8XkG7fYic0SJWZyFdnXNyWvvFOrr/haTn5XtSM454TAvmTQehL5aXV/bKc36j1ZK5xG3xPVOTxwsVssLQ07BXCZYdAIrQ4/l7S1fWW/bdODhq7IYVa1Dew9bHatijUpDuNHe8BgWExNJ0NhKOIVBIXJPRbxv8WpPWUb0oq3ZXjmUUxjx2Ohi6GwFktuqtLx75Cevkh+pUQoHJ9kMPWHdieJOkWJdmPVemzi9j49jwccrFEKAnBkrujdRuAVvpodwQth8wt/GbUVuTwbUQt1+A7VeN8Fvn/246nWNoHfnZLQkO91djAwuTjW2sludbBZfRG+CI2SV9a5NzCzLQtKA7RzjkZDQiw8JrBcokRmL6BPjUxC6YPmKuPxBnhJyENUPRcUGjMRIADSO7jEQ5vqO0gcKSXtvu0yv/I7zMao9wq23hIuR+sBytg7hpsSl2EFkqP7sZkK9G/znfci5Ow0aID9+xZQgxqPPBEA0gHnpDDveh/XwKnnGTZRINKbZPFWJoY8TRKlDDOkFlVoncX03ONMLDEGA8KOfT7Dmgl8HGmujF58qQMUUxBvxSIBMg7LDIAEa2mQUWXE8sFoHwvgqrooBWI4WVtwonzZJSi/xSjFiD+K24lYkKqgCTfOmJlx2bqz60CM=" 
#     skip_cleanup: true
#     upload-dir: travis-builds
#     local_dir: artifacts
  
  
