
on:
  push:
    branches: ['**']

name: build


jobs:
  build:
    runs-on: macos-11

    env:
      R_VERSION: '4.1.3'
      REPO_SNAPSHOT_DATE: "2023-04-07"
      REPO_URL: "https://packagemanager.rstudio.com/cran/2023-04-07"

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
    
    - name: Install R
      run: |
        curl -o R.pkg https://cran.r-project.org/bin/macosx/base/R-$R_VERSION.pkg
        sudo installer -pkg R.pkg -target /
